### ISSUE TITLE
custom config file

### ISSUE THREAD

**Issue by Leolik** [ilyakam/gulp-pug-linter#28]
how use custom .pug-lintrc config file?

**Comment by ilyakam** [comment]
Hello, what happens when you put `.pug-lintrc` file in the same directory as your project (`package.json`, `Gulpfile`, etc.)? It should work the same way.

Также, если Вам будет легче, я могу попробовать​ помочь на русском.

**Comment by Leolik** [comment]
Оо )) отлично
в общем ситуация следующая, я хочу использовать `gulp-pug-linter`, чтобы он отрабатывал после того, как изменились файлы .pug
Для этого создал таску :
```js
gulp.task('puglint', function() {
    return gulp.src('views/**/*.pug')
        .pipe(pugLinter());
});
```
и навешал ее на watcher:
```js
gulp.watch(['views/**/*.{pug,json}'],['pug', 'puglint']);
```

вот содержимое `.pug-lintrc`:
```json
{
    "disallowAttributeConcatenation": true,
    "disallowAttributeInterpolation": true,
    "disallowClassLiteralsBeforeIdLiterals": true,
    "disallowDuplicateAttributes": true,
    "disallowHtmlText": true,
    "disallowLegacyMixinCall": true,
    "disallowMultipleLineBreaks": true,
    "disallowSpacesInsideAttributeBrackets": true,
    "disallowSpecificTags": ["hgroup"],
    "requireClassLiteralsBeforeAttributes": true,
    "requireIdLiteralsBeforeAttributes": true,
    "requireLowerCaseAttributes": true,
    "requireSpecificAttributes": [{
        "img": [ "alt", "width", "height" ]
    }],
    "requireStrictEqualityOperators": true,
    "validateAttributeSeparator": " ",
    "validateExtensions": true,
    "validateIndentation": 2,
    "validateLineBreaks": "LF",
    "validateTemplateString": true
}
```

изначально все завелось и мне казалось, что нормально отрабатывало (показывало ошибки и т.п.), пока не начал делать коммит, на который у меня тоже навешена npm проверка pug уже через консольный `pug-lint`:
```json
"precommit": "echo -n 'pug-lint start...' && pug-lint views && echo -n 'pug-lint finished'"
```
и оказалось, что консольная утилита отрабатывала все правильно, к примеру, при параметре `"validateExtensions": true` при include какого-нибудь файла без указания расширения - вылетала ошибка, при обработке же аналогичной ситуации `gulp-pug-linter` - все проходит без ошибок, тогда-то и выяснил, что ваш плагин не использует мой конфиг, который лежит в проекте

**Comment by Leolik** [comment]
эх, нашел в чем проблема, я изначально попробовал пакет `gulp-pug-lint`, а там не было `.reporter()`, а когда начал пробовать ваш пакет, забыл его указать, теперь все работает нормально )
