### ISSUE TITLE
Deprecation of gulp-util

### ISSUE THREAD

**Issue by michaelcmelton** [ilyakam/gulp-pug-linter#34]
Package gulp-util was deprecated as of December 27, 2017. Recommend replacing gulp-util with plugin-error.

**Comment by ilyakam** [comment]
The actual issue is when running `npm install` as described [in step 4 of the Initial Setup in the Contributing Guide](https://github.com/ilyakam/gulp-pug-linter/blob/develop/CONTRIBUTING.md#initial-setup), it returns the following warning:

```
npm WARN deprecated gulp-util@3.0.8: gulp-util is deprecated - replace it, following the guidelines at https://medium.com/gulpjs/gulp-util-ca3b1f9f9ac5
```
