### ISSUE TITLE
The reporter is not showing up and it breaks the build

### ISSUE THREAD

**Issue by rsancheza09** [ilyakam/gulp-pug-linter#75]
Node Version: 12.13.0
NPM: 6.12.0
gulp-pug-linter: ^1.3.0
puglint-stylish: ^1.0.2

```js
import gulpPugLint from 'gulp-pug-linter';
import pugLintStylish from 'puglint-stylish';

export function lintPug(done) {
  console.log('>>>> STARTING LINT PUG TASK 🖌<<<<');
  done();
  return gulp
      .src('/**/*.pug')
      .pipe(gulpPugLint({
        reporter: pugLintStylish,
      }))
}
```

It breaks the build process on an error, please advice

**Comment by ilyakam** [comment]
Hi @rsancheza09,

There seem to be a couple of issues with your code. I made a few changes and here's what's working for me.

#### Code:

```es6
// gulpfile.js
const gulp = require('gulp');
const gulpPugLint = require('gulp-pug-linter');
const pugLintStylish = require('puglint-stylish');

function lintPug(done) {
  console.log('>>>> STARTING LINT PUG TASK 🖌<<<<');
  done();
  return gulp
      .src('./**/*.pug')
      .pipe(gulpPugLint({
        reporter: pugLintStylish,
      }))
}

exports.lintPug = lintPug;
```

#### Output in Terminal:

<img width="518" alt="terminal-output" src="https://user-images.githubusercontent.com/183227/69835371-eed7c800-11f5-11ea-83c8-b2fa8cf6a6e3.png">

#### The differences are:

1. Correctly export Gulp v4 functions [as seen on its homepage](https://gulpjs.com/) towards the bottom:

    ```diff
    -export function lintPug(done) {
    ```

    ```diff
    +function lintPug(done) {
    +// ...
    +exports.lintPug = lintPug;
    ```

2. Limit the scope to the root of the project to avoid getting "permission denied" errors such as:
    > `Error: EACCES: permission denied, scandir '/Library/[some inaccessible directory]'`

    ```diff
    -.src('/**/*.pug')
    +.src('./**/*.pug')
    ```

I recommend reading up [the Gulp docs](https://gulpjs.com/docs/en/api/concepts) as you are also completing an asynchronous task before it's actually doing anything (see `(done)` and `done()` in your code).

Please mark this issue as resolved if my suggestions had worked for you.

**Comment by ilyakam** [comment]
Hi @rsancheza09, please let me know if this is still an outstanding issue.
Otherwise, I am planning to close it this sometime this weekend.

**Comment by ilyakam** [comment]
Issue closed due to lack of response. If this is still a problem, OP is free to reopen it.
